# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Strategy.Strategy')),
            ],
        ),
    ]
