# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Strategy', '0002_auto_20180820_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.CharField(max_length=100, null=True)),
                ('maxdrawdown', models.CharField(max_length=100, null=True)),
                ('sharp', models.CharField(max_length=100, null=True)),
                ('profitfactor', models.CharField(max_length=100, null=True)),
                ('winrate', models.CharField(max_length=100, null=True)),
                ('std', models.CharField(max_length=100, null=True)),
                ('mean', models.CharField(max_length=100, null=True)),
                ('buynumber', models.CharField(max_length=100, null=True)),
                ('buyprofit', models.CharField(max_length=100, null=True)),
                ('sellnumber', models.CharField(max_length=100, null=True)),
                ('sellprofit', models.CharField(max_length=100, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Strategy.Strategy')),
            ],
        ),
    ]
