# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='info',
            field=models.CharField(max_length=500),
        ),
    ]
